---
- include_vars: ../vars/variables.yml
- name: download software zip file
  get_url:
    url: "{{ software_url }}"
    dest: "{{ vault_home_path }}"
    mode: '755'

- name: "unzip software"
  unarchive:
    src: "{{ vault_home_path }}/{{ vault_zip_file }}"
    dest: "/opt/vault/bin"
  become: true

- name: "configure vault location"
  file:
    path: "/etc/vault"
    state: directory

- name: "config.json file"
  template:
    src: "config_json.j2"
    dest: "/etc/vault/config.json"
  become: true

- name: "move the files to /etc/services"
  template:
    src: vault_service.j2
    dest: "/etc/systemd/system/vault.service"

- name: "enable and start services"
  service:
    name: vault
    state: started
    enabled: yes
