---
- include_vars: ../vars/variables.yml
- name: "create group"
  group:
    name: "{{ group_name }}"
    state: present
  become: true

- name: create vault user
  user:
    name: "{{ user_name }}"
    uid: "{{ user_id }}"
    group: "{{ group_name }}"
    state: present
  become: true

- name: Allow 'vault' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%vault ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: "add authorized key in vault user"
  authorized_key:
    user: "{{ user_name }}"
    key: '{{ item }}'
  with_file:
    - ../templates/vault_server_ssh_key.j2
  

- name: "create vault data directory"
  file:
    path: "{{ vault_data_dir_path }}"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ group_name }}"

- name: "create vault log directory"
  file:
    path: "{{ vault_log_dir_path }}"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ group_name }}"

- name: "create vault log directory"
  file:
    path: "{{ vault_bin_location }}"
    state: directory
  become: true

- name: Install the latest version of unzip
  yum:
    name: unzip
    state: latest